import{a as b,S,i as n}from"./assets/vendor-9cRawSbk.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const M="52917262-bfaf5bd23aa54a80b60e2fad9",O="https://pixabay.com/api/";async function d(t,s,a=15){const o=new URLSearchParams({key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:a,page:s});return(await b.get(`${O}?${o}`)).data}function g(t){return t.map(({webformatURL:a,largeImageURL:o,tags:e,likes:r,views:c,comments:y,downloads:L})=>`
            <li class='gallery-list-item'>
                <a href='${o}' class='gallery-item-link'>
                    <img src='${a}' class='gallery-item-image' alt='${e}'/>
                    <div class='gallery-item-info'>
                        <p class='gallery-info-item'>Likes <span>${r}</span></p>
                        <p class='gallery-info-item'>Views <span>${c}</span></p>
                        <p class='gallery-info-item'>Comments <span>${y}</span></p>
                        <p class='gallery-info-item'>Downloads <span>${L}</span></p>
                    </div>
                </a>
            </li>
        `).join("")}const i={form:document.querySelector(".form"),formInput:document.querySelector(".gallery-form-input"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".load-more-btn")};let h=new S(".gallery-item-link",{captionsData:"alt",captionDelay:250}),l=1;const f=15;let p="";const $=()=>{const{height:t}=i.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})},m=(t=!1)=>{i.loader.classList.toggle("hidden",!t)},u=(t=!1)=>{i.loadMore.classList.toggle("hidden",!t)},k=async t=>{t.preventDefault();const s=t.currentTarget,a=i.formInput.value.trim();if(a===""){n.error({message:"Please enter a search term.",position:"topRight"});return}l=1,p=a,i.gallery.innerHTML="",u(!1),m(!0);try{const o=await d(p,l,f),e=Math.ceil(o.totalHits/f);if(o.hits.length===0){n.error({message:"No images found. Please try a different search term.",position:"topRight",closeOnClick:!0});return}const r=g(o.hits);i.gallery.innerHTML=r,h.refresh(),l<e?u(!0):n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results.",closeOnClick:!0})}catch(o){n.error({message:`Error: ${o.message}`,position:"topRight",closeOnClick:!0})}finally{m(!1),s.reset()}},v=async()=>{l++,m(!0),u(!1);try{const t=await d(p,l,f),s=Math.ceil(t.totalHits/f),a=g(t.hits);i.gallery.insertAdjacentHTML("beforeend",a),h.refresh(),$(),l<s?u(!0):(u(!1),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results.",closeOnClick:!0}))}catch(t){n.error({message:`Error: ${t.message}`,position:"topRight",closeOnClick:!0})}finally{m(!1)}};i.form.addEventListener("submit",k);i.loadMore.addEventListener("click",v);
//# sourceMappingURL=index.js.map
