import{a as y,S as L,i as n}from"./assets/vendor-9cRawSbk.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const v="52917262-bfaf5bd23aa54a80b60e2fad9",M="https://pixabay.com/api/";async function m(i,r,s=15){const o=new URLSearchParams({key:v,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:r});return(await y.get(`${M}?${o}`)).data}function u(i){return i.map(({webformatURL:s,largeImageURL:o,tags:t,likes:a,views:l,comments:h,downloads:g})=>`
            <li class='gallery-list-item'>
                <a href='${o}' class='gallery-item-link'>
                    <img src='${s}' class='gallery-item-image' alt='${t}'/>
                    <div class='gallery-item-info'>
                        <p class='gallery-info-item'>Likes <span>${a}</span></p>
                        <p class='gallery-info-item'>Views <span>${l}</span></p>
                        <p class='gallery-info-item'>Comments <span>${h}</span></p>
                        <p class='gallery-info-item'>Downloads <span>${g}</span></p>
                    </div>
                </a>
            </li>
        `).join("")}const e={form:document.querySelector(".form"),formInput:document.querySelector(".gallery-form-input"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".load-more-btn")};let p=new L(".gallery-item-link",{captionsData:"alt",captionDelay:250}),d=1,c=15,f="";const b=()=>{const{height:i}=e.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})},S=async i=>{try{e.loadMore.classList.add("hidden"),e.loader.classList.remove("hidden"),d++;const r=await m(f,d,c),s=Math.ceil(r.totalHits/c);if(r.hits.length===0){e.loadMore.classList.add("hidden");return}const o=u(r.hits);if(e.gallery.insertAdjacentHTML("beforeend",o),e.loadMore.classList.remove("hidden"),e.loader.classList.add("hidden"),b(),p.refresh(),d>=s){e.loader.classList.add("hidden"),e.loadMore.classList.add("hidden"),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});return}}catch(r){console.log(r)}};e.form.addEventListener("submit",async i=>{i.preventDefault();const r=e.formInput.value.trim();if(f=r,r===""){n.error({message:"Please enter a search term.",position:"topRight",closeOnClick:!0});return}e.gallery.innerHTML="",e.gallery.classList.add("hidden"),e.loader.classList.remove("hidden");try{const s=await m(r,d),o=Math.ceil(s.totalHits/50);if(e.formInput.value="",e.loadMore.classList.add("hidden"),s.hits.length===0){n.error({message:"No images found. Please try a different search term.",position:"topRight",closeOnClick:!0}),e.loader.classList.add("hidden"),e.loadMore.classList.add("hidden"),e.gallery.classList.remove("hidden");return}const t=u(s.hits);e.gallery.insertAdjacentHTML("beforeend",t),e.loader.classList.add("hidden"),e.loadMore.classList.remove("hidden"),d>=o&&(e.loader.classList.add("hidden"),e.loadMore.classList.add("hidden"),n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})),e.loadMore.addEventListener("click",S),p.refresh()}catch(s){n.error({message:`Error: ${s.message}`,position:"topRight",closeOnClick:!0})}finally{e.loader.classList.add("hidden"),e.gallery.classList.remove("hidden")}});
//# sourceMappingURL=index.js.map
